version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_${APP_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ./${RESULT_FILE}:/var/www/html/${RESULT_FILE}
      - ./${LOG_FILE}:/var/www/html/${LOG_FILE}
    networks:
      - web_provise

networks:
  web_provise:
    driver: bridge
